### ISSUE TITLE
Release package PR summary shows merge commit author not PR author

### ISSUE THREAD

**Issue by taldcroft** [sot/skare3_tools#81]
Not a huge deal but it is a bit confusing that the release summary report does not reflect the real author of a PR, e.g. this one by @jeanconn that I merged:

PR 31 (taldcroft): Update maneuver regex to parse prelim neg obsids

**Comment by javierggt** [comment]
I'm going over the issues in the change summary, and I do not remember if this was fixed. Do you remember which repository was this PR 31? or some PR that was merged from someone other than the author?

I think this is fixed, because the following code lists xija PR 129 created by John and merged by Tom:
```python
from skare3_tools import packages
repo_info = packages.get_repository_info('sot/xija', update=True, since=8)
release_info = {r['release_tag']: r for r in repo_info['release_info']}
release_info['4.29.0']['merges']
```
output:
```
[{'pr_number': 129,
  'branch': 'jzuhone/heat_refactor',
  'title': 'Refactor heat.py into a subpackage',
  'author': 'John ZuHone'}]
```
